// Build-time embedder: reads prompts/system_prompt.md and prompts/cv_response_schema.json
// from the workspace, generates worker/src/embedded.generated.ts so the Worker has a
// single source of truth. Workers cannot read files at runtime; everything must be
// baked into the JS bundle at build time.
//
// Run automatically by wrangler before `deploy` / `dev` via the [build] command in
// wrangler.toml. Also runnable directly: `node scripts/embed-prompts.mjs`.
//
// The generated file is gitignored — it always derives from the source files.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const workerRoot = resolve(here, "..");
const promptsDir = resolve(workerRoot, "..", "prompts");

const systemPromptPath = resolve(promptsDir, "system_prompt.md");
const schemaPath = resolve(promptsDir, "cv_response_schema.json");
const outPath = resolve(workerRoot, "src", "embedded.generated.ts");

// Normalize CRLF -> LF before fingerprinting so Windows autocrlf checkouts produce
// the same fingerprint as Linux/CI checkouts. Without this, the deployed worker's
// fingerprint mismatches a freshly-checked-out tree on Windows.
function readLF(p) {
  return readFileSync(p, "utf8").replace(/\r\n/g, "\n");
}
const systemPrompt = readLF(systemPromptPath);
const schemaText = readLF(schemaPath);

// Validate schema parses as JSON before embedding.
let schemaParsed;
try {
  schemaParsed = JSON.parse(schemaText);
} catch (err) {
  console.error(`[embed-prompts] FATAL: ${schemaPath} is not valid JSON: ${err.message}`);
  process.exit(1);
}

// Compute a short fingerprint so the generated file is auditable.
function fnv1a(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}
const promptFingerprint = fnv1a(systemPrompt);
const schemaFingerprint = fnv1a(schemaText);

// Escape the prompt for embedding as a JS string literal inside backticks.
// We need to escape: backtick, backslash, and ${ (template-literal interpolation).
const escapedPrompt = systemPrompt
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const generated = `// AUTO-GENERATED FILE — DO NOT EDIT.
// Regenerated by scripts/embed-prompts.mjs from:
//   prompts/system_prompt.md       (fingerprint ${promptFingerprint})
//   prompts/cv_response_schema.json (fingerprint ${schemaFingerprint})
// Generated at: ${new Date().toISOString()}
//
// To update the prompt or schema, edit the source files in prompts/ and rebuild.

export const SYSTEM_PROMPT = \`${escapedPrompt}\`;

export const RESPONSE_SCHEMA: object = ${JSON.stringify(schemaParsed, null, 2)};

export const PROMPT_FINGERPRINT = "${promptFingerprint}";
export const SCHEMA_FINGERPRINT = "${schemaFingerprint}";
`;

writeFileSync(outPath, generated, "utf8");
console.log(`[embed-prompts] wrote ${outPath}`);
console.log(`  prompt fingerprint: ${promptFingerprint} (${systemPrompt.length} chars)`);
console.log(`  schema fingerprint: ${schemaFingerprint} (${schemaText.length} chars)`);
