"""
generate_registry.py

Scans all Python scripts in the execution/ directory and regenerates REGISTRY.md.
Each script should have a module-level docstring in this format:

    \"\"\"
    description: One-line description of what this script does
    inputs: What it takes (files, args, env vars)
    outputs: What it produces (files, API calls, stdout)
    \"\"\"

Usage:
    python execution/generate_registry.py
"""

import os
import ast
from pathlib import Path
from datetime import date

EXECUTION_DIR = Path(__file__).parent
REGISTRY_PATH = EXECUTION_DIR / "REGISTRY.md"

SKIP_FILES = {"generate_registry.py", "__init__.py"}


def extract_docstring_fields(filepath: Path) -> dict:
    """Parse a script's module-level docstring for registry fields."""
    try:
        source = filepath.read_text(encoding="utf-8")
        tree = ast.parse(source)
        docstring = ast.get_docstring(tree) or ""
    except Exception:
        return {}

    fields = {"description": "", "inputs": "", "outputs": ""}
    for line in docstring.splitlines():
        for key in fields:
            if line.strip().lower().startswith(f"{key}:"):
                fields[key] = line.split(":", 1)[1].strip()
    return fields


def build_registry() -> str:
    scripts = sorted(
        p for p in EXECUTION_DIR.glob("*.py") if p.name not in SKIP_FILES
    )

    rows = []
    for script in scripts:
        fields = extract_docstring_fields(script)
        rows.append(
            f"| `{script.name}` "
            f"| {fields.get('description') or '—'} "
            f"| {fields.get('inputs') or '—'} "
            f"| {fields.get('outputs') or '—'} |"
        )

    table = "\n".join(rows) if rows else "| *(none yet)* | | | |"

    return f"""# Execution Registry

This file is auto-generated by `generate_registry.py`. Do not edit manually.
Run `python execution/generate_registry.py` after adding or modifying any script.
Last updated: {date.today()}

## Scripts

| Script | Description | Inputs | Outputs |
|--------|-------------|--------|---------|
{table}
"""


if __name__ == "__main__":
    content = build_registry()
    REGISTRY_PATH.write_text(content, encoding="utf-8")
    print(f"Registry updated: {REGISTRY_PATH}")
    print(f"Scripts found: {content.count('| `')}")
