// src/lib/reviews.mjs — build-time review loader.
//
// Reads src/content/reviews.json (generated by scripts/sync_reviews.mjs
// during `npm run prebuild`), falling back to reviews-seed.json (checked
// into the repo) if the generated file is missing. Used by Testimonials,
// ReviewsGrid, /reviews page, and Base.astro (JSON-LD aggregate).
//
// Exported as a plain function so any Astro component can call it in its
// frontmatter without an import cycle:
//     import { loadReviews } from '../lib/reviews.mjs';
//     const { reviews, count, average_rating } = loadReviews();

import fs from 'node:fs';
import path from 'node:path';

// Astro's static build runs with cwd = project root, so anchoring on
// process.cwd() is more reliable than import.meta.url — Vite may rewrite
// the module URL during bundling, causing readFileSync path resolution
// to silently miss.
const CONTENT_DIR = path.resolve(process.cwd(), 'src/content');
const REVIEWS_JSON = path.join(CONTENT_DIR, 'reviews.json');
const SEED_JSON = path.join(CONTENT_DIR, 'reviews-seed.json');

// 2026-08-04 — silent-now fingerprint. Same heuristic as reviews-public.ts.
// verified imports whose submitted_at and approved_at are within 60s are
// tagged 'unknown' so the renderer can say "date pending verification"
// instead of a falsely-precise month. Kept in sync with the API side by
// convention — if you change one, change the other.
const SILENT_NOW_WINDOW_MS = 60 * 1000;
export function computeDateProvenance(r) {
  if (!r || !r.verified) return 'provided';
  if (!r.submitted_at || !r.approved_at) return 'provided';
  const s = Date.parse(r.submitted_at);
  const a = Date.parse(r.approved_at);
  if (!Number.isFinite(s) || !Number.isFinite(a)) return 'provided';
  if (Math.abs(a - s) < SILENT_NOW_WINDOW_MS) return 'unknown';
  return 'provided';
}

function normalizeSeed(r) {
  // NEVER silent-default missing dates to `new Date()` — that was the exact
  // 2026-07 bug shape. If a date is missing we leave it null and let the
  // provenance heuristic flag the record downstream. Seed rows in the repo
  // are curated with real dates; KV rows are validated on write.
  const submitted_at = r.submitted_at || null;
  const approved_at = r.approved_at || r.submitted_at || null;
  const record = {
    id: r.id,
    name: r.name,
    rating: Number(r.rating) || 5,
    body: r.body || r.body_fr || r.body_en || '',
    body_fr: r.body_fr || null,
    body_en: r.body_en || null,
    source: r.source || 'other',
    source_url: r.source_url || null,
    lang: r.lang || 'fr',
    submitted_at,
    approved_at,
    featured: !!r.featured,
    verified: !!r.verified,
  };
  // Honor an API-supplied value if present (reviews-public.ts computes it
  // per record); otherwise compute here so the SSG output matches.
  record.date_provenance = r.date_provenance || computeDateProvenance(record);
  return record;
}

function sortReviews(list) {
  list.sort((a, b) => {
    if (a.featured !== b.featured) return a.featured ? -1 : 1;
    // Unknown-provenance rows sort by approved_at (the only trustworthy
    // timestamp); known ones by submitted_at (the actual review date).
    // Keeps a silent-now-stamped July 2026 row from out-ranking a real
    // June 2026 review.
    const ak =
      (a.date_provenance === 'unknown' ? a.approved_at : a.submitted_at) ||
      a.approved_at ||
      '';
    const bk =
      (b.date_provenance === 'unknown' ? b.approved_at : b.submitted_at) ||
      b.approved_at ||
      '';
    return bk.localeCompare(ak);
  });
  return list;
}

function computeAggregate(list) {
  if (!list.length) return { count: 0, average_rating: null };
  const total = list.reduce((s, r) => s + (Number(r.rating) || 0), 0);
  return {
    count: list.length,
    average_rating: Math.round((total / list.length) * 10) / 10,
  };
}

export function loadReviews() {
  // Prefer the generated file (fresh from KV via prebuild).
  try {
    const raw = fs.readFileSync(REVIEWS_JSON, 'utf8');
    const parsed = JSON.parse(raw);
    if (parsed && Array.isArray(parsed.reviews)) {
      const list = parsed.reviews.map(normalizeSeed);
      sortReviews(list);
      const agg = computeAggregate(list);
      return { ...agg, reviews: list, source: parsed._source || 'generated' };
    }
  } catch {
    /* fall through to seed */
  }

  // Fallback: read the checked-in seed (bootstrap builds, offline dev).
  try {
    const raw = fs.readFileSync(SEED_JSON, 'utf8');
    const parsed = JSON.parse(raw);
    const list = Array.isArray(parsed.reviews) ? parsed.reviews.map(normalizeSeed) : [];
    sortReviews(list);
    const agg = computeAggregate(list);
    return { ...agg, reviews: list, source: 'seed' };
  } catch {
    return { count: 0, average_rating: null, reviews: [], source: 'empty' };
  }
}

// Convenience: pick the right body string for a language.
export function pickBody(r, lang) {
  if (lang === 'en') return r.body_en || r.body || r.body_fr || '';
  return r.body_fr || r.body || r.body_en || '';
}

// Human-readable source label, per lang.
export function sourceLabel(source, lang) {
  const fr = {
    onsite: 'Site',
    superprof: 'Superprof',
    meetup: 'Meetup',
    trainme: 'TrainMe',
    instagram: 'Instagram',
    email: 'Recommandation',
    other: 'Autre',
  };
  const en = {
    onsite: 'On-site',
    superprof: 'Superprof',
    meetup: 'Meetup',
    trainme: 'TrainMe',
    instagram: 'Instagram',
    email: 'Recommendation',
    other: 'Other',
  };
  return (lang === 'en' ? en : fr)[source] || (lang === 'en' ? en.other : fr.other);
}
