"""
description: Build dist/job-digest-skill.zip — the standalone bundle a friend installs at
    ~/.claude/skills/job-digest/ (SKILL.md + CHANGELOG.md + the job_digest engine + a pinned
    requirements.txt + the friend-facing README). Refuses to build if the bundle would leak
    any operator-personal literal (see BLOCKLIST below).
inputs: none (reads .claude/skills/job-digest/, execution/personal_workflows/job_digest/,
    execution/personal_workflows/job_digest/templates/README_FRIEND.md if present, and the
    workspace root requirements.txt for version pins)
outputs: dist/job-digest-skill.zip; prints the bundle tree and final size; exit 0 on success,
    exit 2 (listing offending files) if the blocklist scan finds a personal literal
"""
from __future__ import annotations

import shutil
import sys
import tempfile
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILL_SRC = REPO_ROOT / ".claude" / "skills" / "job-digest"
ENGINE_SRC = REPO_ROOT / "execution" / "personal_workflows" / "job_digest"
README_FRIEND = ENGINE_SRC / "templates" / "README_FRIEND.md"
ROOT_REQUIREMENTS = REPO_ROOT / "requirements.txt"
DIST_DIR = REPO_ROOT / "dist"
ZIP_NAME = "job-digest-skill.zip"

# Refuse to build if any bundled file contains one of these literals (case-insensitive
# for the name/emails). These are operator-specific to job_search_v2 / this workspace and
# must never leak into a bundle a friend installs standalone.
# - operator's surname (git log / GitHub author on this repo)
# - the two operator Gmail addresses (job_search_v2/sources/remoteok.py User-Agent contact,
#   and the workspace-owner account this session runs as)
# - "job_search_v2": the operator's own isolated pipeline; job_digest must never name it
# - "profile.json": job_search_v2's own profile file name, distinct from job_digest's
#   profile.yaml — its presence in job_digest code would mean an accidental cross-reference
# - _TEST_MARKER: a synthetic, never-real literal tests/test_package.py plants to prove the
#   scan actually fires, so no real operator email needs to live in the test suite.
_TEST_MARKER = "blocklist-canary-@example.invalid"

BLOCKLIST: tuple[str, ...] = (
    "mazumdar",
    "debanjan186@gmail.com",
    "debolshop@gmail.com",
    "job_search_v2",
    "profile.json",
    _TEST_MARKER,
)

# Only the deps the engine's own modules import (see execution/personal_workflows/job_digest/**).
# Version pins are copied from the workspace root requirements.txt when a line for that
# package exists there; otherwise a conservative pin is chosen here.
ENGINE_DEPS = {
    "pydantic": None,
    "pyyaml": None,
    "httpx": None,
    "beautifulsoup4": None,
    "gspread": None,
    "google-auth": "google-auth>=2.30.0",
    "google-genai": None,
    "anthropic": None,
}

# "fixtures" is deliberately NOT excluded: job_digest.tests's offline jsonl
# fixtures live under job_digest/fixtures/ (not tests/fixtures/) so the
# standalone bundle's `run --mode dry` has something to fetch — only the
# tests/ package itself (pytest files, not the fixtures data it reads) is
# excluded.
EXCLUDE_DIR_NAMES = {"tests", "__pycache__", ".tmp", ".pytest_cache", "state"}


def _iter_engine_files():
    for path in ENGINE_SRC.rglob("*"):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(ENGINE_SRC).parts
        if any(part in EXCLUDE_DIR_NAMES for part in rel_parts):
            continue
        if path.suffix == ".pyc":
            continue
        yield path


def _resolve_requirements() -> str:
    root_lines: dict[str, str] = {}
    if ROOT_REQUIREMENTS.exists():
        for line in ROOT_REQUIREMENTS.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            name = stripped.split(">=")[0].split("==")[0].split("<")[0].strip().lower()
            root_lines[name] = stripped

    out_lines = [
        "# Auto-generated by scripts/package_job_digest.py — only the deps job_digest's",
        "# own modules import. Do not hand-edit; edit the workspace root requirements.txt",
        "# and re-run the packaging script instead.",
    ]
    for pkg, fallback in ENGINE_DEPS.items():
        line = root_lines.get(pkg)
        if line is None:
            line = fallback or pkg
        out_lines.append(line)
    return "\n".join(out_lines) + "\n"


def _resolve_readme() -> str:
    if README_FRIEND.exists():
        return README_FRIEND.read_text(encoding="utf-8")
    return (
        "# Job Digest\n\n"
        "This README will be generated from the engine's "
        "`templates/README_FRIEND.md` once it exists. For now, see "
        "`SKILL.md` in this bundle and run `/job-digest setup` from Claude "
        "Code to get started.\n"
    )


def _scan_blocklist(root: Path) -> list[tuple[Path, str]]:
    """Return [(file, matched_literal), ...] for every offending file under root."""
    offenders: list[tuple[Path, str]] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore").lower()
        except (UnicodeDecodeError, OSError):
            continue
        for literal in BLOCKLIST:
            if literal.lower() in text:
                offenders.append((path, literal))
    return offenders


def build(dist_dir: Path = DIST_DIR, zip_name: str = ZIP_NAME) -> Path:
    if not SKILL_SRC.exists():
        raise SystemExit(f"missing skill source: {SKILL_SRC}")
    if not ENGINE_SRC.exists():
        raise SystemExit(f"missing engine source: {ENGINE_SRC}")

    with tempfile.TemporaryDirectory(prefix="job-digest-bundle-") as tmp:
        stage = Path(tmp) / "job-digest"
        stage.mkdir(parents=True)

        shutil.copy2(SKILL_SRC / "SKILL.md", stage / "SKILL.md")
        shutil.copy2(SKILL_SRC / "CHANGELOG.md", stage / "CHANGELOG.md")

        engine_dest_root = stage / "engine" / "job_digest"
        engine_dest_root.mkdir(parents=True)
        for src_file in _iter_engine_files():
            rel = src_file.relative_to(ENGINE_SRC)
            dest = engine_dest_root / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_file, dest)

        (stage / "engine" / "requirements.txt").write_text(_resolve_requirements(), encoding="utf-8")
        (stage / "README.md").write_text(_resolve_readme(), encoding="utf-8")

        offenders = _scan_blocklist(stage)
        if offenders:
            print("REFUSED: personal/operator-specific literal(s) found in bundle:", file=sys.stderr)
            for path, literal in offenders:
                print(f"  - {path.relative_to(stage)}: matched {literal!r}", file=sys.stderr)
            raise SystemExit(2)

        dist_dir.mkdir(parents=True, exist_ok=True)
        zip_path = dist_dir / zip_name
        if zip_path.exists():
            zip_path.unlink()
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in sorted(stage.rglob("*")):
                if f.is_file():
                    zf.write(f, arcname=f.relative_to(stage.parent))

        _print_tree(stage)
        size = zip_path.stat().st_size
        print(f"\nWrote {zip_path} ({size:,} bytes)")
        return zip_path


def _print_tree(stage: Path) -> None:
    print(f"{stage.name}/")
    for f in sorted(stage.rglob("*")):
        rel = f.relative_to(stage)
        indent = "  " * len(rel.parts)
        marker = "/" if f.is_dir() else ""
        print(f"{indent}{rel.name}{marker}")


if __name__ == "__main__":
    build()
